### ISSUE TITLE
启动错误 

### ISSUE THREAD

**Issue by lyb-ops** [philippnormann/chia-monitor#1]
![image](https://user-images.githubusercontent.com/63178995/121357887-c0978480-c964-11eb-8dbb-1ce45a8d9d64.png)

**Comment by lyb-ops** [comment]
在我的ubuntu主机上

**Comment by philippnormann** [comment]
Looks, like your farmer daemon is not running. Are you running chia-monitor on the same machine as your farmer?

**Comment by lyb-ops** [comment]
![image](https://user-images.githubusercontent.com/63178995/121363174-461d3380-c969-11eb-99f6-b088d5042a50.png)
是的在一台机器上

**Comment by lyb-ops** [comment]
非常需要您的帮助

**Comment by lyb-ops** [comment]
Your help is badly needed

**Comment by philippnormann** [comment]
That process is a plotting process and not the farmer.  Did you run `chia start farm` on that machine?
Plot process monitoring is not part of this tool yet. What are you trying to monitor?

**Comment by lyb-ops** [comment]
I mean my machine is running a chia process and I need a cool Grafana interface

**Comment by lyb-ops** [comment]
But now your work is having some problems with my machine

**Comment by lyb-ops** [comment]
![image](https://user-images.githubusercontent.com/63178995/121367137-a366b400-c96c-11eb-9217-737c750fe225.png)
Is it because the path to the chia key file cannot be found

**Comment by lyb-ops** [comment]
I can't find your conf file

**Comment by lyb-ops** [comment]
![Uploading image.png…]()

**Comment by lyb-ops** [comment]
![image](https://user-images.githubusercontent.com/63178995/121368771-e6755700-c96d-11eb-8482-b710d31ad963.png)

**Comment by philippnormann** [comment]
> I mean my machine is running a chia process and I need a cool Grafana interface

Like I mentioned, not all Chia processes can be monitored by this tool yet. The main focus right now is to monitor all farmer related statistics. So if you aren't running a farmer on your system, there is nothing this tool can monitor and it fails to start.

What output does `chia farm summary`  give you?

**Comment by lyb-ops** [comment]
I see what you mean. Thank you for your help
