### ISSUE TITLE
Using IP address as unique constraint

### ISSUE THREAD

**Issue by madbuda** [philippnormann/chia-monitor#11]
My harvesters are all behind a NAT / VPN so they all show up with the same ip address

Running monitor gives the following exception 
sqlite3.IntegrityError: UNIQUE constraint failed: harvester_events.ts
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: harvester_events.ts
[SQL: INSERT INTO harvester_events (ts, plot_count, portable_plot_count, plot_size, portable_plot_size, host) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('2021-07-10 19:24:21.317341', 153, 0, 16649650377080, 0, 'X.X.X.X')]

Possibly use the Node ID and not the IP address?

**Comment by madbuda** [comment]
strange, I moved all my harvesters to have unique addresses and still get the same error

```
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: harvester_events.ts
[SQL: INSERT INTO harvester_events (ts, plot_count, portable_plot_count, plot_size, portable_plot_size, host) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('2021-07-10 21:40:24.491908', 132, 0, 14364854277227, 0, '10.9.0.3')]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

```
![image](https://user-images.githubusercontent.com/2191492/125180401-aa7d1e00-e1c7-11eb-8c4b-e374e9e9e894.png)

**Comment by philippnormann** [comment]
Hey @madbuda, thanks for the bug report!

I pushed an update that should resolve your issue.
Can you please give it a try and tell me if it works?
