### ISSUE TITLE
Add option to turn off "Proof found!" notifications

### ISSUE THREAD

**Issue by F1DNA** [philippnormann/chia-monitor#13]
As the title states, with pool plots, we don't need to see 100's of notifications throughout the day anymore
You could differentiate between a partial and a full so we can still be alerted if we actually find a proof, whether via OG or pool plots
Of course, seeing all of these notifications lets us know that things are working, to some degree
Perhaps you could incorporate some of the notifications in chiadog such as skipped signage points, "did not participate in any challenges for X time", etc

**Comment by philippnormann** [comment]
Thanks for the suggestions! I fixed your main issue in the latest version and I'll see what I can do about additional alerts and ways how we can differentiate between pooling proofs and OG proofs in the future.
