### ISSUE TITLE
websocket can't connect, how to solve

### ISSUE THREAD

**Issue by 774406683** [philippnormann/chia-monitor#19]
websocket can't connect, how to solve

**Comment by 774406683** [comment]
Provisional headers are shown

**Comment by 774406683** [comment]
Provisional headers are shown
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cache-Control: no-cache
Connection: Upgrade
Cookie: grafana_session=bac46117b98e199565beb293f7df8bbb
Host: 36.158.231.8:3000
Origin: http://36.158.231.8:3000
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: h30ThN8BbJLV8JULA9hw+w==
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

**Comment by 774406683** [comment]
@philippnormann

**Comment by 774406683** [comment]
websocket can't connect, how to solve

**Comment by 774406683** [comment]
websocket can't connect, how to solve

**Comment by philippnormann** [comment]
Hey @774406683, please stop spamming other issues. I saw this, but your comments didn't provide enough information for me to identify the root cause of your issue. Please provide detailed error logs and a description of the setup you are running this on.
