### ISSUE TITLE
Notification instability, possibly due to concurrent access to sqlite db?

### ISSUE THREAD

**Issue by cmatthias** [philippnormann/chia-monitor#21]
Hi there,

Thanks for the awesome project! I'm having some trouble using this project with my farm. The code is connecting to the Chia RPC endpoints and getting data just fine, but the summary notifications seem to consistently break. I'm using discord for notifications, but I don't believe the issue is specific to the notification provider used.

The usual pattern I see is that I get one notification sent successfully, and then nothing after that. This error will show up in the console, typically within a few minutes of starting up:

```
2021-07-13T17:25:38.316 ERROR  Failed to retrieve event from DB. Please initialize DB using: 'pipenv run alembic upgrade head'
```

After instrumenting the code a bit to print more stack trace and exception info, it looks like the underlying error is typically saying that the database is locked, e.g.:

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT sum(anon_1.plot_count) AS sum_1
FROM (SELECT max(harvester_events.plot_count) AS plot_count
FROM harvester_events
WHERE harvester_events.ts > ? GROUP BY harvester_events.host) AS anon_1]
[parameters: ('2021-07-13 17:25:03.302213',)]
```

This error is always thrown in `notifier.py` in the `await asyncio.gather(*tasks)` call.

I've attempted to rule out any DB corruption issues by deleting my DB and re-running alembic to create a fresh DB, but that doesn't seem to make any difference.

Have you seen any issues like this in the past? Could it be due to multiple coroutines attempting to use the DB simultaneously?

Happy to provide additional logs/context, just let me know. Thanks!

**Comment by philippnormann** [comment]
Hey @cmatthias, thanks for the elaborate bug report and your initial debugging efforts 🙂 
You are the first one reporting this kind of issue, but I agree with your suspicion that too many concurrent queries to the DB might be the root cause. We could try to reduce the number of simultaneous queries by awaiting the notifications sequentially. 

Could you try to replace the following lines in `notifier.py`
```python
tasks = [n.run() for n in self.notifications]
await asyncio.gather(*tasks)
```
with
```python
for notification in self.notifications:
    await notification.run()
```
and report if that helps to resolve your issue?

**Comment by 774406683** [comment]
@philippnormann 
Why not answer my websocket question，wuwuwuwuwuwu

**Comment by cmatthias** [comment]
Hi @philippnormann, thanks for the reply! I first tried making that change but was still receiving the same error, unfortunately.

However, I'm now testing an additional fix, which involves adding a couple of arguments to `create_async_engine` in `monitor/database/__init__.py`. Setting up the engine using the following line has resulted in no "database is locked" errors for about 20 minutes, which is way better than what I was seeing before.

```
engine = create_async_engine(DATABASE_URL, echo=False, connect_args={'timeout': 30.0, 'isolation_level': None})
```

The reason I tried this was that I guessed that somewhere in the code a `commit()` was being missed, resulting in a transaction locking the DB for longer than it should. As far as I understand it, the `timeout: 30` arg means "wait for the lock to be released for up to 30 sec before throwing an exception", and the `isolation_level: None` arg [forces the python sqlite library to use autocommit mode](https://docs.python.org/3/library/sqlite3.html#sqlite3-controlling-transactions).

 I also have the "sequential await" fix that you suggested in place still. Not sure if that's required with the above changes but I will test it out.

I am sure that the timeout arg is probably too long, and I'm not sure how you feel about autocommit mode, but these changes make things more stable for me. I will let this run for some time today and report back. Thanks again!

**Comment by philippnormann** [comment]
Hey @cmatthias, I don't feel great about this kind of workaround, but I also failed to find any mistake in our DB usage and therfore suspect the bug to lie somewhere in the async implementation of SQLAlchemy. For now, enabling `AUTOCOMMIT` and increasing the timeout seems like a good way to mitigate the issue. The [documentation](https://docs.sqlalchemy.org/en/14/dialects/sqlite.html#transaction-isolation-level-autocommit) I found suggests slightly different parameters:
```python
engine = create_async_engine(DATABASE_URL,
                             echo=False,
                             isolation_level="AUTOCOMMIT",
                             connect_args={'timeout': 30.0})
```
Not sure if it makes any difference, but I would definitely be curious to hear your results for this variant and the one you suggested without the "sequential await" fix. Thanks again for being so helpful!

**Comment by cmatthias** [comment]
Hey again @philippnormann, thanks for the extra info! It turns out I did eventually get DB lock errors (after about an hour) with my original set of changes. I just changed the `isolation_level` argument to the style you suggested (which I agree looks right based on the docs) and I'll let you know if that does any better.

**Comment by cmatthias** [comment]
Looks like I'm still seeing this issue even with your suggested change. I'm racking my brain trying to figure out why no one else sees this, because it's consistently reproducible on my machine. I'm on an Ubuntu 21.04 VM running python 3.9.5, which doesn't seem like it'd be an unusual setup. The underlying storage for the VM is an SSD (so it's not unusually slow). I am running my full chia node, wallet, and harvester on the same machine, so maybe that has something to do with it?

Any other thoughts/ideas would be most welcome :) Thanks for your help so far!

**Comment by madbuda** [comment]
Was seeing something similar, no errors, but I need to restart a few times a day to get notifications back

**Comment by cmatthias** [comment]
Hi @philippnormann, wanted to updated you on this issue: I discovered there was a configuration issue with the VM that I was running my chia node and chia-monitor on. The VM's disk image was living on an NFS-mounted directory on the host, meaning the VM's storage was not local to the host and instead was going out over a (probably overtaxed) gigabit network. I discovered this after noticing some other weird I/O behavior on the VM (unrelated to chia-monitor).

After moving the VM's disk to be local on the VM host, this issue disappeared and I have been successfully receiving notifications, even after backing out the changes you suggested earlier in the thread. I'm not 100% sure if there is still an underlying issue in the code that was exposed by my probably-close-to-worst-case I/O scenario, but I'll close this issue for now since the issue as I was experiencing it is resolved.

If you'd still like to investigate more, feel free to reopen this, and now that I know how to reproduce the issue I could set a VM back up for testing any potential fixes.

Thanks so much for your help!
