### ISSUE TITLE
Send logs to my remote grafana server?

### ISSUE THREAD

**Issue by brianjojoray** [philippnormann/chia-monitor#22]
I have a remote grafana server that i want to use .
From your guide, I can not find any where to config remote grafana server.
please help~

**Comment by philippnormann** [comment]
Hey @brianjojoray, you need a Prometheus server to collect the metrics and a Grafana server to visualize them. They can be anywhere in your network, as long as they can reach your farmer. Then you need to configure Prometheus as described in the README and add it as data source to Grafana. After that, you can import the dashboard and should see your farming metrics.
