### ISSUE TITLE
grafana: Data not refreshing fast enough in dashboard

### ISSUE THREAD

**Issue by charnet3d** [philippnormann/chia-monitor#28]
I noticed that the panels in the dashboard weren't refreshing fast enough (even when chia-monitor has read new values). They stay out of sync quite a while and when I open an individual panel and focus some of the fields in the query UI then it gets the new values. I looked up this issue online and it seems to be known in grafana.

https://community.grafana.com/t/data-is-not-refreshing-in-grafana-dashboard-but-refreshing-in-panel/41138

One of the workarounds being suggested was to open "Query Options" and setting "Max Data Points" to some high value like 999999. I tried this on all panels and now the refreshing of the dashboard seems to follow more closely the realtime values.

Maybe the provided grafana dashboard.json can be updated with this.

**Comment by philippnormann** [comment]
Hey @charnet3d, thanks for the suggestion! I increased the max data points in the `dashboard.json`, and now the stats displayed in the panels are always up to date 👍🏽
