### ISSUE TITLE
random db crash

### ISSUE THREAD

**Issue by SAVAMforWIN** [philippnormann/chia-monitor#35]
after starting the chia monitor it crashes producing the following errors

![image](https://user-images.githubusercontent.com/34774419/126912187-f56d82ca-9f79-4ece-829d-76eb6894b51b.png)

**Comment by charnet3d** [comment]
Hi,
If you get the message "Failed to persist event to DB" then try deleting "history.sqlite" and running "pipenv run alembic upgrade head" once again to regenerate the database.

**Comment by SAVAMforWIN** [comment]
hello thanks, where can I find the history.sqlite file?, I have already tried to rebuild the db without success but I have not deleted the file you told me

**Comment by charnet3d** [comment]
If the command for generating the DB isn't successful then not I'm not sure what could be the issue. Check what message it returns in that step.

**Comment by SAVAMforWIN** [comment]
the command generates this report for me

![image](https://user-images.githubusercontent.com/34774419/127673521-071dd122-38a3-47b5-87f8-e7df259cb15d.png)

**Comment by charnet3d** [comment]
When it shows like that it means the DB exists. But it could need an upgrade if you had updated the code files.
Go into the root of chia-monitor and delete the history.sqlite file, it's definitely there. When you delete it and regenerate the DB it should give you an output like this:

![image](https://user-images.githubusercontent.com/2863796/127685074-95372703-b5e1-4cec-b362-3a76c0798d7e.png)

**Comment by SAVAMforWIN** [comment]
i tried to delete history.sqlite and rebuild the DB but after a few minutes it crashes again
