### ISSUE TITLE
Enhancement Req: Include Time for Plot Checks

### ISSUE THREAD

**Issue by gilperme** [philippnormann/chia-monitor#37]
Thank you for a great tool to keep an eye on our farms. One thing that I think is important to track and helpful in understanding the health of a node is the speed of the plot checks. It looks like you're capturing all the key elements except the speed of the check. Would it be possible to include this in a future release?

Here's an example from the log file:

_"6 plots were eligible for farming a1e9e688b1... Found 0 proofs. Time: 0.61389 s. Total 790 plots"_

Again you're already capturing # of plots eligible, # of proofs found and total number of plots. Only thing missing is the time. 

Please let me know if you need any additional information or help. Thanks in advance for your consideration.

**Comment by philippnormann** [comment]
Fixed in https://github.com/philippnormann/chia-monitor/commit/97d034e8e3564d44a44d817163996264ff0dd20e
