### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by TheBrigandRo** [philippnormann/chia-monitor#4]
PC Specs: Windows 10, Ryzen 9 3900x, B550 Steel Legend, NO GPU.
Python: 3.8.10,   Chia: 1.1.7
The PC is it used with Remote Desktop Connection, the error happens some time (this time 10 min) after I have disconnected from the PC.
The Error is large so I put it in a .txt file. [Error.txt](https://github.com/philippnormann/chia-monitor/files/6676903/Error.txt)

**Comment by philippnormann** [comment]
Hey @TheBrigandRo, thanks for reporting this issue!

This seems to be a very rare event which I haven't run in to yet on my setup. 

The error you posted seems to imply that you received multiple signage points at exactly the same timestamp, causing a index collision in the database when the we try to insert this event.

Did this error reoccur after you restarted the monitor?

**Comment by TheBrigandRo** [comment]
Well, I don't have a monitor connected (no gpu). I am controlling the PC with the Remote Desktop Connection from windows.
And every time I connect to the PC it's like logging in the user, but when I disconnect the programs keeps running.
And the problem keeps happening, it not something rare on my end.
Is there a way to check the collision and prevented, or just a simple try, catch :))

**Comment by philippnormann** [comment]
With monitor I was actually referring to this program and not an actual computer monitor 😄 Since you are the only person reporting this issue I suspect this seems to be something weird with your setup and I suggest we move this discussion to our discord #support channel which you can join using the link in the README.md.

**Comment by nvg58** [comment]
@philippnormann the issue I reported is the same as this
