### ISSUE TITLE
Near future changes to INFO log-level by chia devs

### ISSUE THREAD

**Issue by gryan315** [philippnormann/chia-monitor#52]
Saw this mentioned in the flexpool discord and thought I'd give you a heads up:

> Sargonas — Today at 9:12 PM
Info is a funny thing.. it wasn't meant to be run day to day, as it's super I/O and resourece intensive.. but you DO need it for like, 90% of the monitoring tools out there. So we're trying to move things out of it monitoring tools don't need and/or make a new class of "monitoring" between info and warn that ONLY has what tools want/need. Alternatively maybe we can make hooks for tools to get info from less resource heavy methods. I have some ongoing chats with Foxy (dashboard) and Gil (farmr) and a few others about how we can make this easier for them and less effort on your nodes.

**Comment by philippnormann** [comment]
Hey @gryan315, thanks for the heads up! I think we're fine, since we don't read INFO logs and instead use the RPC and WebSocket APIs of the node. I'll still try to talk to Sargonas directly to make sure we're in line with the planned changes.

**Comment by sargonas** [comment]
Ohai :)

Just letting you know it's probably okay to close this one out. None of those proposed changes are happening anytime soon as we've backburnered making these changes for now, and even if we did, looking at your stuff seems like you don't use the info logs anyways and rely on the preferred method of RPC anyways. :)

**Comment by philippnormann** [comment]
Thanks for your feedback @sargonas!
