### ISSUE TITLE
support 1.2.0

### ISSUE THREAD

**Issue by KevinMyDing** [philippnormann/chia-monitor#6]
Are there plans to support the latest 1.2.0 protocol?
The current version will be incompatible when using the 1.2.0 protocol

**Comment by philippnormann** [comment]
Hey @KevinMyDing,

I updated the code to use the new `get_harvesters` RPC call from the 1.2.0 release and also split up monitoring for OG and portable plots. Please feel free to open a new issue if you have any other feature requests :)
