### ISSUE TITLE
is there a log file location I can troubleshoot from?

### ISSUE THREAD

**Issue by sargonas** [philippnormann/chia-monitor#67]
In the last day I have had repeated crashes within 20-30 minutes of starting things, across all 3 systems I run it on. Each time it ends with a core dump and little useful info. Is there a log file somewhere I am not finding I can be looking at to get to the bottom of things? (I have a sneaking suspicion there might be a breaking change in 1.3 that may be adding new info to the log files perhaps it is breaking over.. but so far I cant diagnose enough to get to the root of it.)

(FWIW that I am running it from screen, since I have had difficulty up until now running it as a service and haven't had time diving into getting that working yet.)

(Edit: seems I got a different error this time, which is a first and partially descriptive)
```
munmap_chunk(): invalid pointer
Aborted (core dumped)
```

**Comment by stefan-lange** [comment]
I start chia-monitor in my custom docker image with `/opt/chia-monitor/.venv/bin/python -m monitor >/dev/null 2>&1 &`
and it seems to work. At least prometheus/grafana and service alerts via telegram bot.

To collect logs you could use `.venv/bin/python -m monitor >~/my-chia-monitor.log`

I am using chia `1.3.1`, debian `10`, python `3.9`

**Comment by sargonas** [comment]
Thanks!

I actually got this resolved but then hopped on a flight and forgot to come back here and close this. :D

Based on some advice from someone in our public Keybase server, I got rid of the sqlite file which had just gotten... bulky, and once it was gone everything worked fine. I think it just got bloated or had some weird data in it, no big deal.
