### ISSUE TITLE
Can you add the new pool_state details?

### ISSUE THREAD

**Issue by gryan315** [philippnormann/chia-monitor#9]
Would be nice to see pool points and points successful % on the dashboard.

**Comment by philippnormann** [comment]
Thanks for the suggestion @gryan315! 

I added the found points, acknowledged points and the resulting success rate to the dashboard.

**Comment by gryan315** [comment]
Thanks again for adding this functionality, I'm curious as to how multiple pools are handled by the API. Is what's shown in the dashboard just from the first pool nft? For example, If I have 1st pool at difficulty 4, and 2nd pool at difficulty 1, the difficulty 4 is all that's shown.

**Comment by philippnormann** [comment]
Hey @gryan315, the initial version was actually hardcoded to use the first plot NFT. 

In the latest version, we now collect information from all plot NFTs and have a drop-down menu in the dashboard where you can choose which pools stats you want to display. Hope this helps 🙂

**Comment by gryan315** [comment]
You're quick

**Comment by gryan315** [comment]
Sorry to keep posting in this closed thread, but I was thinking about another enhancement to these metrics. Would it be feasible to add the number of plots associated with a pool_contract_puzzle_hash/p2_singleton_puzzle_hash (are these different or the same value in the RPC?) for each pool under the get_pool_state collector? Would be convenient to show that data under each pool in the dropdown, and cleaner than displaying several different Portable Plot size boxes for all of the plotnfts at once.
